### ISSUE TITLE
(not an issue) Autojoin between Vita and VitaTV works just fine

### ISSUE THREAD

**Issue by rsn8887** [fgsfdsfgs/chocolate-doom#8]
Quick report: I just tested autojoin netplay between my VitaTV and Vita (using current git build), and it works perfectly. I just selected "host game" on the VitaTV and "autojoin" on the Vita and I am now playing two player Doom!

(The text mode works great, too, btw!)

**Comment by fgsfdsfgs** [comment]
Great, thank you for testing. I have updated the code to take my SDL_net changes into account (98fd0e9). Could you test it again on the latest commit to check for any possible regressions?

**Comment by rsn8887** [comment]
Still works perfectly.

**Comment by fgsfdsfgs** [comment]
Thanks.
